### ISSUE TITLE
XML Docs for wholegraph needs to be created and uploaded in ci for use by cugraph-docs repository

### ISSUE THREAD

**Issue by acostadon** [rapidsai/cugraph-gnn#94]
This was done prior to migration into gnn

https://github.com/rapidsai/wholegraph/blob/branch-24.12/ci/build_docs.sh

**Comment by jameslamb** [comment]
References for context:

* discussion about why this is needed: https://github.com/rapidsai/cugraph-docs/pull/46#issuecomment-2541919930
* how this works in `cugraph`: https://github.com/rapidsai/cugraph/blob/3ad4949f2e119f881361500172a04d2d4b243f31/ci/build_docs.sh#L63-L68
* how it used to work in `wholegraph`: https://github.com/rapidsai/wholegraph/blob/0a10aba7242656839dfcb31c7eba8b12df106631/ci/build_docs.sh#L35-L38

**Comment by jameslamb** [comment]
Reopening as this wasn't actually fixed by #96 (see #97).

**Comment by jameslamb** [comment]
Ok NOW we can close this, this was uploaded in https://github.com/rapidsai/cugraph-gnn/actions/runs/12381312765

And I saw that XML get downloaded successfully in https://github.com/rapidsai/cugraph-docs/pull/46
